-- “LOT 중심 통합 조회” 한 방 쿼리
SELECT
    LM.LOT_NO,
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    WO.WORK_ORDER_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    PH.GOOD_QTY,
    PH.NG_QTY,
    DL.DEFECT_CODE,
    DL.DEFECT_NAME,
    DL.DEFECT_QTY,
    MU.MATERIAL_CODE,
    MU.MATERIAL_NAME,
    MU.USED_QTY,
    SM.SHIPMENT_NO,
    SD.SHIP_QTY
FROM LOT_MASTER LM
JOIN ITEM_MASTER IM
  ON LM.ITEM_ID = IM.ITEM_ID
JOIN WORK_ORDER WO
  ON LM.WORK_ORDER_ID = WO.WORK_ORDER_ID
LEFT JOIN PROCESS_HISTORY PH
  ON LM.LOT_ID = PH.LOT_ID
LEFT JOIN DEFECT_LOG DL
  ON PH.PROCESS_HIST_ID = DL.PROCESS_HIST_ID
LEFT JOIN MATERIAL_USAGE MU
  ON PH.PROCESS_HIST_ID = MU.PROCESS_HIST_ID
LEFT JOIN SHIPMENT_DETAIL SD
  ON LM.LOT_ID = SD.LOT_ID
LEFT JOIN SHIPMENT_MASTER SM
  ON SD.SHIPMENT_ID = SM.SHIPMENT_ID
ORDER BY LM.LOT_NO, PH.PROCESS_HIST_ID;













-- 거래처별 생산지시 현황
SELECT
    CM.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    WO.WORK_ORDER_NO,
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    WO.PLAN_QTY,
    WO.DUE_DATE,
    WO.ORDER_STATUS,
    WO.CREATED_AT
FROM CUSTOMER_MASTER CM
JOIN WORK_ORDER WO
  ON CM.CUSTOMER_ID = WO.CUSTOMER_ID
JOIN ITEM_MASTER IM
  ON WO.ITEM_ID = IM.ITEM_ID
ORDER BY CM.CUSTOMER_NAME, WO.WORK_ORDER_NO;

-- 거래처별 주문 집계
SELECT
    CM.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    COUNT(WO.WORK_ORDER_ID) AS ORDER_COUNT,
    SUM(WO.PLAN_QTY) AS TOTAL_PLAN_QTY
FROM CUSTOMER_MASTER CM
LEFT JOIN WORK_ORDER WO
  ON CM.CUSTOMER_ID = WO.CUSTOMER_ID
GROUP BY CM.CUSTOMER_CODE, CM.CUSTOMER_NAME
ORDER BY CM.CUSTOMER_NAME;

-- 작업지시별 LOT 진행 현황
SELECT
    WO.WORK_ORDER_NO,
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    WO.PLAN_QTY,
    WO.DUE_DATE,
    WO.ORDER_STATUS,
    LM.LOT_NO,
    LM.LOT_QTY,
    LM.CURRENT_STEP_NO,
    LM.LOT_STATUS,
    LM.START_DT,
    LM.END_DT
FROM WORK_ORDER WO
JOIN ITEM_MASTER IM
  ON WO.ITEM_ID = IM.ITEM_ID
LEFT JOIN LOT_MASTER LM
  ON WO.WORK_ORDER_ID = LM.WORK_ORDER_ID
ORDER BY WO.WORK_ORDER_NO, LM.LOT_NO;


-- 작업지시별 진행률 포함 조회
SELECT
    WO.WORK_ORDER_NO,
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    LM.LOT_NO,
    LM.LOT_STATUS,
    LM.CURRENT_STEP_NO,
    FN_GET_LOT_PROGRESS_RATE(LM.LOT_NO) AS PROGRESS_RATE
FROM WORK_ORDER WO
JOIN ITEM_MASTER IM
  ON WO.ITEM_ID = IM.ITEM_ID
JOIN LOT_MASTER LM
  ON WO.WORK_ORDER_ID = LM.WORK_ORDER_ID
ORDER BY WO.WORK_ORDER_NO, LM.LOT_NO;

-- LOT Trace / 공정이력 조회 
SELECT
    LM.LOT_NO,
    PH.PROCESS_HIST_ID,
    PRS.STEP_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    PH.START_TIME,
    PH.END_TIME,
    PH.INPUT_QTY,
    PH.GOOD_QTY,
    PH.NG_QTY,
    PH.PROCESS_STATUS
FROM LOT_MASTER LM
JOIN PROCESS_HISTORY PH
  ON LM.LOT_ID = PH.LOT_ID
JOIN PROCESS_ROUTE_STEP PRS
  ON PH.ROUTE_STEP_ID = PRS.ROUTE_STEP_ID
ORDER BY LM.LOT_NO, PRS.STEP_NO;


-- 작업자별 공정현황
SELECT
    UM.USER_CODE,
    UM.USER_NAME,
    LM.LOT_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    PH.START_TIME,
    PH.END_TIME,
    PH.INPUT_QTY,
    PH.GOOD_QTY,
    PH.NG_QTY,
    PH.PROCESS_STATUS
FROM USER_MASTER UM
JOIN PROCESS_HISTORY PH
  ON UM.USER_ID = PH.USER_ID
JOIN LOT_MASTER LM
  ON PH.LOT_ID = LM.LOT_ID
ORDER BY UM.USER_NAME, PH.START_TIME;

-- 품목별 공정현황
SELECT
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    LM.LOT_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    PH.INPUT_QTY,
    PH.GOOD_QTY,
    PH.NG_QTY,
    PH.PROCESS_STATUS
FROM ITEM_MASTER IM
JOIN LOT_MASTER LM
  ON IM.ITEM_ID = LM.ITEM_ID
JOIN PROCESS_HISTORY PH
  ON LM.LOT_ID = PH.LOT_ID
ORDER BY IM.ITEM_CODE, LM.LOT_NO, PH.PROCESS_HIST_ID;

-- 설비별 공정현황
SELECT
    EM.EQUIPMENT_CODE,
    EM.EQUIPMENT_NAME,
    LM.LOT_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    PH.START_TIME,
    PH.END_TIME,
    PH.INPUT_QTY,
    PH.GOOD_QTY,
    PH.NG_QTY
FROM EQUIPMENT_MASTER EM
JOIN PROCESS_HISTORY PH
  ON EM.EQUIPMENT_ID = PH.EQUIPMENT_ID
JOIN LOT_MASTER LM
  ON PH.LOT_ID = LM.LOT_ID
ORDER BY EM.EQUIPMENT_CODE, PH.START_TIME;

-- 출하현황
SELECT
    SM.SHIPMENT_NO,
    SM.SHIPMENT_DATE,
    CM.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    LM.LOT_NO,
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    SD.SHIP_QTY,
    SM.SHIPMENT_STATUS
FROM SHIPMENT_MASTER SM
JOIN CUSTOMER_MASTER CM
  ON SM.CUSTOMER_ID = CM.CUSTOMER_ID
JOIN SHIPMENT_DETAIL SD
  ON SM.SHIPMENT_ID = SD.SHIPMENT_ID
JOIN LOT_MASTER LM
  ON SD.LOT_ID = LM.LOT_ID
JOIN ITEM_MASTER IM
  ON LM.ITEM_ID = IM.ITEM_ID
ORDER BY SM.SHIPMENT_DATE, SM.SHIPMENT_NO;

-- 거래처별 출하현황 집계
SELECT
    CM.CUSTOMER_CODE,
    CM.CUSTOMER_NAME,
    COUNT(SM.SHIPMENT_ID) AS SHIPMENT_COUNT,
    SUM(SD.SHIP_QTY) AS TOTAL_SHIP_QTY
FROM CUSTOMER_MASTER CM
JOIN SHIPMENT_MASTER SM
  ON CM.CUSTOMER_ID = SM.CUSTOMER_ID
JOIN SHIPMENT_DETAIL SD
  ON SM.SHIPMENT_ID = SD.SHIPMENT_ID
GROUP BY CM.CUSTOMER_CODE, CM.CUSTOMER_NAME
ORDER BY CM.CUSTOMER_NAME;

-- 제품불량 현황
SELECT
    LM.LOT_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    DL.DEFECT_CODE,
    DL.DEFECT_NAME,
    DL.DEFECT_QTY,
    DL.DEFECT_REASON,
    DL.CREATED_AT
FROM DEFECT_LOG DL
JOIN LOT_MASTER LM
  ON DL.LOT_ID = LM.LOT_ID
LEFT JOIN PROCESS_HISTORY PH
  ON DL.PROCESS_HIST_ID = PH.PROCESS_HIST_ID
ORDER BY LM.LOT_NO, DL.DEFECT_ID;

-- 품목별 불량 집계
SELECT
    IM.ITEM_CODE,
    IM.ITEM_NAME,
    DL.DEFECT_CODE,
    DL.DEFECT_NAME,
    SUM(DL.DEFECT_QTY) AS TOTAL_DEFECT_QTY
FROM DEFECT_LOG DL
JOIN LOT_MASTER LM
  ON DL.LOT_ID = LM.LOT_ID
JOIN ITEM_MASTER IM
  ON LM.ITEM_ID = IM.ITEM_ID
GROUP BY IM.ITEM_CODE, IM.ITEM_NAME, DL.DEFECT_CODE, DL.DEFECT_NAME
ORDER BY IM.ITEM_CODE, DL.DEFECT_CODE;

-- 공정별 불량 집계
SELECT
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    DL.DEFECT_CODE,
    DL.DEFECT_NAME,
    SUM(DL.DEFECT_QTY) AS TOTAL_DEFECT_QTY
FROM DEFECT_LOG DL
JOIN PROCESS_HISTORY PH
  ON DL.PROCESS_HIST_ID = PH.PROCESS_HIST_ID
GROUP BY PH.PROCESS_CODE, PH.PROCESS_NAME, DL.DEFECT_CODE, DL.DEFECT_NAME
ORDER BY PH.PROCESS_CODE, DL.DEFECT_CODE;

-- 자재사용 이력
SELECT
    LM.LOT_NO,
    PH.PROCESS_CODE,
    PH.PROCESS_NAME,
    MU.MATERIAL_CODE,
    MU.MATERIAL_NAME,
    MU.MATERIAL_LOT_NO,
    MU.USED_QTY,
    MU.UNIT,
    MU.CREATED_AT
FROM MATERIAL_USAGE MU
JOIN LOT_MASTER LM
  ON MU.LOT_ID = LM.LOT_ID
LEFT JOIN PROCESS_HISTORY PH
  ON MU.PROCESS_HIST_ID = PH.PROCESS_HIST_ID
ORDER BY LM.LOT_NO, MU.MATERIAL_USAGE_ID;

-- 자재별 사용 집계
SELECT
    MU.MATERIAL_CODE,
    MU.MATERIAL_NAME,
    SUM(MU.USED_QTY) AS TOTAL_USED_QTY,
    MU.UNIT
FROM MATERIAL_USAGE MU
GROUP BY MU.MATERIAL_CODE, MU.MATERIAL_NAME, MU.UNIT
ORDER BY MU.MATERIAL_CODE;

